apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: VSphereCPIConfig
metadata:
  name: testworkload
  namespace: default
spec:
  vsphereCPI:
    mode: vsphereCPI
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    vmNetwork:
      excludeExternalSubnetCidr: 10.156.159.89/32
      excludeInternalSubnetCidr: 10.156.159.89/32
---
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: ClusterBootstrap
metadata:
  annotations:
    tkg.tanzu.vmware.com/add-missing-fields-from-tkr: v1.24.9---vmware.1-tkg.1
  name: testworkload
  namespace: default
spec:
  additionalPackages:
  - refName: metrics-server*
  - refName: secretgen-controller*
  - refName: pinniped*
  cpi:
    refName: vsphere-cpi*
    valuesFrom:
      providerRef:
        apiGroup: cpi.tanzu.vmware.com
        kind: VSphereCPIConfig
        name: testworkload
  kapp:
    refName: kapp-controller*
---
apiVersion: v1
kind: Secret
metadata:
  name: testworkload
  namespace: default
stringData:
  password: P@ssw0rd
  username: tkg-user@vsphere.local
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: photon,3,amd64
    tkg.tanzu.vmware.com/cluster-controlplane-endpoint: 10.156.159.89
    tkg/plan: prod
  labels:
    tkg.tanzu.vmware.com/cluster-name: testworkload
  name: testworkload
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  topology:
    class: tkg-vsphere-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
      replicas: 3
    variables:
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: auditLogging
      value:
        enabled: true
    - name: podSecurityStandard
      value:
        audit: baseline
        deactivated: false
        warn: baseline
    - name: apiServerEndpoint
      value: 10.156.159.89
    - name: aviAPIServerHAProvider
      value: false
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: /TDC
        datastore: /TDC/datastore/vsanDatastore
        folder: /TDC/vm/TKG
        network: /TDC/network/tkg-network
        resourcePool: /TDC/host/TCluster/Resources
        server: vcva8.vsanpe.vmware.com
        storagePolicyID: ""
        template: /TDC/vm/Discovered virtual machine/photon-3
        tlsThumbprint: 30:45:7C:24:2D:4B:C6:20:8D:C7:9F:F2:BA:31:84:C6:3D:29:ED:7A
    - name: user
      value:
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqR3wgUAMWWGrnAFquG1dspI5tyZNgwabhQ632yt+Vbwrut2u+D0bdDzJirrzOahmXjRYndFByUFilVsGtejuCg5XpJB+a2Ab5Y5fV5raysrKKeKvGRcQWkDNHn6ABUjV9EU/+IkRk9rZgE8STjk0TQEh8Nq+joNj9g6XDuJAXRpqFaADvs5N5cjRJYFcYdJFJ5wSP1+PlYTxUDTw4lxHVRdxtgR88FOOwGMJ9GXEnha2NOqpIZ/SJzB6u/CRCJS7TRNFmDzJy9diPUrG2L5m9Av4/B6i2km0bs22CZqzoFf2WaKpAcbngfUbcBTY0dMKZhQ0DtgrSRgVVkM0pak/eAnxSljD26N6RvsnyAkIZ+2/n1N6A+ku62HoemUgHhMVWAEJoDwu94KnE/sUbKkYwM+LWhq8ALV3aIwYsOj/YU7PwpmZdvGn3lO+cF39jC85TdmI4kzn3xaHmQVBLOE80/nnCnk63zJlKPRJB0aPajzVbvcWUKiuCC5i1J1YM4l+GneNVyDnLxF/5+bgLalhsOkfN7fTMUDwUs7dUGpGF/l7U2MUeAwrl/WiWLlDpCsvG+lpD+MSTrpxW3uGugrnUcABpW/fMOpT/BZgu0NdMRar4fDphuymVhjZriVzqJIYHrQV7ZIVhHIMDNXx4UiekPEDG2XOw6rKJUvIofyvp0w==
    - name: controlPlane
      value:
        machine:
          diskGiB: 40
          memoryMiB: 8192
          numCPUs: 2
    - name: worker
      value:
        count: 1
        machine:
          diskGiB: 40
          memoryMiB: 65536
          numCPUs: 16
    version: v1.24.9+vmware.1
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-0
        replicas: 1
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-1
        replicas: 1
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-2
        replicas: 1
